### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-skycrawlers#1]
This this library as a gem.
``` ruby
# Gemfile
gem 'daimon_skycrawlers'
```

It should provide some commands such as the followings:

``` sh
$ daimon-skycrawlers generate
$ daimon-skycrawlers init
$ daimon-skycrawlers crawler start
$ daimon-skycrawlers processor start
```

**Comment by okkez** [comment]
Prefer `setup`, `db:setup`  or `queue:setup`  than `init`.

**Comment by okkez** [comment]
`daimon-skycrowlers start [crawler|processor]` is prefer.

**Comment by tricknotes** [comment]
`setup` command is another issue: https://github.com/bm-sms/daimon-skycrawlers/issues/9

**Comment by okkez** [comment]
New project has DB related rake tasks.

**Comment by tricknotes** [comment]
ひとまず OK !
