### ISSUE TITLE
Filter crawling URL API

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-skycrawlers#4]

**Comment by tricknotes** [comment]
ref: https://github.com/scrapy/scrapy

**Comment by tricknotes** [comment]
nice to have: "Consider 'Content-Type '"

**Comment by okkez** [comment]
`PatternFilter` filters before enqueue urls.
`ContentTypeFilter` filters before store content to storage.

**Comment by okkez** [comment]
#23
