### ISSUE TITLE
どのような使われ方を想定しているのかわからなかった

### ISSUE THREAD

**Issue by yucao24hours** [bm-sms/daimon-skycrawlers#56]
この gem を使ってできるクローラープロジェクトが、rails などでできたアプリケーションに組み込む用途を前提にしているのか、独立して使用される用途を前提にしているのかがちょっと把握しきれませんでした 💦 

README を見ると、crawler 用プロジェクトをつくるには

```sh
$ bundle exec daimon-skycrawlers new mycrawler
```

とあるので、 rails などの Gemfile を持ったプロジェクトの配下に `mycrawler` プロジェクトをつくるような使用方法を想定しているのかなというふうに想像していました。

一方で、 `mycrawler` 用の DB はその名前を使って `mycrawler_development` などのように作られるので、複数のアプリケーションプロジェクトで `mycrawler` という同名のクローラーを作って migrate しようとした場合、結果として DB を共用するようなことになって

```sh
PG::DuplicateTable: ERROR:  relation "pages" already exists
: CREATE TABLE "pages" ("id" serial primary key, "url" character varying, "headers" text, "body" bytea, "last_modified_at" timestamp, "etag" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)
```

が出ます。
アプリケーションプロジェクトごとにクローラープロジェクトを持つような形を想定しているとしたら、このエラーが出るのはチョット使いづらいかなと感じました。
クローラープロジェクトが独立して存在するような形を想定しているとしたら、それがわかるような記載などにすることが必要かもしれません。（記載を変えるだけですむのか把握しきれてませんが... 😓 ）

**Comment by okkez** [comment]
独立して使用することを想定しています。今のところRailsアプリケーションに組込むことは想定していません。
ProcessorからRailsアプリケーション(または、他のアプリケーション)で使用しているDBに書き込むことは想定しています。(きちんと動作するかどうか、わかっていません)

`bundle exec ...` は手元で動作させていたときの名残りなので `gem i daimon-skycrawlers` で入れていたらいらないです。

DB名の重複については、自動で回避はできなさそうです。Railsでも、同名のアプリケーションを別ディレクトリで作ると同じことが起こります。重複が困るなら今のところ database.yml を書き換えるしか方法はないと思います。

来週、READMEの記述を見直してみます。

**Comment by yucao24hours** [comment]
ありがとうございます！
DB 名が重複することがこまるなあと思っていたのはあくまでも

>アプリケーションプロジェクトごとにクローラープロジェクトを持つような形を想定しているとしたら

という仮定をしてのことでした。
独立して使用することを想定しているということですので

>DB名の重複については、自動で回避はできなさそうです。

というままで構わないとおもいました！（感想）
