### ISSUE TITLE
Drop perfectqueue

### ISSUE THREAD

**Issue by tricknotes** [bm-sms/daimon-skycrawlers#6]
Good bye MySQL.

**Comment by okkez** [comment]
mysql しかサポートしてない。。。

https://github.com/treasure-data/perfectqueue/blob/master/lib/perfectqueue/backend/rdb_compat.rb#L73

**Comment by okkez** [comment]
* [QueueClassic](https://github.com/QueueClassic/queue_classic)
  * PostgreSQL の LISTEN/NOTIFY を使って実装されたやつ
* RabbitMQ
  * @tricknotes が使ったことのあるMQ

RabbitMQ にした方がよさそう。

**Comment by tricknotes** [comment]
:memo: 

> A gem for processing tasks asynchronously, powered by RabbitMQ.

https://github.com/songkick/queue

> A Ruby job queue that uses PostgreSQL's advisory locks for speed and reliability.

https://github.com/chanks/que
