### ISSUE TITLE
DaimonSkycrawlers::Filter::UpdateChecker の名前について

### ISSUE THREAD

**Issue by yucao24hours** [bm-sms/daimon-skycrawlers#70]
`DaimonSkycrawlers::Filter::UpdateChecker` は `call` メソッドを呼ぶことで役割を果たしてくれますが、`call` メソッドが true を返すときというのは「更新されていたとき」なのか「更新されていなかったとき」なのかが名前から判断しづらく、最終的に何をしているのかコードを読まないとわかりませんでした。
`DaimonSkycrawlers::Filter::DuplicateChecker` も同様でした。

**Comment by okkez** [comment]
ドキュメントを書けば解決しそうな雰囲気ですね。。。
`DimonSkycrawlers::Filter::*` のフィルターについては、後続の処理を実行したいときに true を返し、後続の処理を実行したくないときに false を返すというルールで作っています。
(というのをドキュメントに書きたい気持ちを表明しておきます)

**Comment by yucao24hours** [comment]
なるほど、ルール理解しました！
ドキュメントがあるとユーザにとってはよりよい助けになると思います 👍 

ただ、
```ruby
unless update_checker.call(url.to_s, connection: connection)
  ...
end
```

というコードだけを一見したときに、この `unless` の中に入るのがどんな時なのかを理解するのはちょっと難しいなあ、というのが率直な感想でした。
ルールやその内容をコードの中で表すのがそれぞれの "名前" だと思うので、名前を変えるというのも手段のひとつとしてありかな〜と思いました！

**Comment by okkez** [comment]
filter ごとに call に別名を付けて、個別に使うときは別名の方を使うようにしました。
