### ISSUE TITLE
robots.txt によって拒否されているか否かのチェックについて

### ISSUE THREAD

**Issue by yucao24hours** [bm-sms/daimon-skycrawlers#72]
default クローラの `fetch` メソッドに記述されていた

```ruby
if @options[:obey_robots_txt]
  robots_txt_checker = DaimonSkycrawlers::Filter::RobotsTxtChecker.new(base_url: @base_url)
  unless robots_txt_checker.call(url)
    skip(url)
    return
  end
end
```

は、あらゆるクローラにおいて実行されるべきだと思うので、ユーザがわざわざ （`Crawler::Base` クラスを継承した各自のクローラクラスで）書かずに済むようにしてもらえたほうがありがたいかなと思いました。
（ところで、 `if @options[:obey_robots_txt]` となっているということは `false` をセットして robots.txt を無視できるようにもできる作りなのだと解釈したんですが、もしそうだとしたらちょっとマズそうな気がしましたがどうなんでしょうか💧 ）

**Comment by okkez** [comment]
[Downloader Middleware — Scrapy 1.2.0 documentation](https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware) によると Scrapy でもデフォルトでは robots.txt を読まないようなので、デフォルトで読まないのはそれでいいかなぁ、と思います。現状、デフォルトでは robots.txt を読まないようになっています。
他のクローラーでも robots.txt はオプショナルな扱いだったと思います。

> あらゆるクローラにおいて実行されるべきだと思う

これについては、ちょっと考えてみます。

**Comment by okkez** [comment]
対応した。
