### ISSUE TITLE
timestamps カラムの型について

### ISSUE THREAD

**Issue by yucao24hours** [bm-sms/daimon-skycrawlers#79]
プロジェクトを `new` したときに generate されるマイグレーションファイルの `timestamps` カラムが、以前は `t.timestamps` だったのですが今は `t.string :timestamps` となるのは、意図通りでしたかね...？
https://github.com/bm-sms/daimon-skycrawlers/blob/a27437deccb5acf1956cc71747d0ada23a114c5d/lib/daimon_skycrawlers/storage/rdb.rb#L24-L30 このあたりとか見て特にそういった意図の変更はなさそうなような気がしないでもなかったので、ねんのため。。

```ruby
class CreatePage < ActiveRecord::Migration[5.0]
  def change
    create_table :pages do |t|
      t.string :url
      t.text :headers
      t.binary :body
      t.datetime :last_modified_at
      t.string :etag
      t.string :timestamps
    end
  end
end
```

**Comment by okkez** [comment]
あー、間違えてますね。。。
ぷるりくください :pray:

**Comment by okkez** [comment]
なおしてみました。

**Comment by yucao24hours** [comment]
おそくてすみません。トライしてみようと思ってジェネレータのつくりを調べてたところでした 😓 
ご対応ありがとうございます！

**Comment by okkez** [comment]
もう少し待てばよかったですね。。。
